Added training function
mdolab/baseclasses pull request #21
Opened 2020-11-26 03:13 UTC by nwu63

## Purpose
This PR added a new function `setTrainingMode` which is used in place of `setRef` for those regression tests that have to modify `self.train` after creating the object. This is used for example by ADflow.

Also, I added a new `check` option to the various `add_vals` except for the `add_dict` function. If not in training mode, setting `check=True` will compare an existing value with what's being added, instead of adding a new value. This is useful when the tests generate two values that should match. Instead of adding both to the reference file, we can now add just one, and use the `check=True` option to check the other value against it. To facilitate this, the `getTol` function now passes back an updated `kwargs` dictionary with the tolerances trimmed off, which is then passed to the underlying `add_values` functions.

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
I added a few new tests.

## Checklist
_Put an `x` in the boxes that apply._

- [ ] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [x] I have run unit and regression tests which pass locally with my changes
- [x] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

2020-11-27 23:03 UTC, eirikurj requested changes
See my comments, we can also have a chat if this is unclear. Functionally this is fine but there I am wondering if there should be a more general way of setting the `mode` that this is run in. Using e.g., a `setMode` function that sets `self.mode = "train"` variable that dictates the mode.

2020-11-27 23:22 UTC, nwu63 commented
Many good points there. Let's have a chat offline about some specifics, but the main thing I wanted to say here is that I am still struggling a bit with this approach. The issue is that, there is no easy way to leverage `setUp()` functions when writing tests, since instantiation of the `BaseRegTest` class requires the mode to be set. Therefore, there are two existing approaches:
- separate training and testing functions, and separate instantiation of the `BaseRegTest` class. This is not great because of code duplication
- instantiate in `setUp` with `train=False` by default. In the training function, override this with something like the `setTrainingMode` function. This is also problematic because in the instantiation, if `train=False` then we read in the reference file, so if we actually want to train then this will throw an error if the file does not already exist.

I haven't found a good solution yet, maybe create another class that inherits from both BaseRegTest and unittest.TestCase or something? I'm sure there's a clean pythonic solution somewhere.

2020-11-29 18:49 UTC, nwu63 commented
I have updated the PR by removing the `setTrainingMode` function which is no longer needed. Also addressed the other comments.

2020-12-01 13:02 UTC, eirikurj approved these changes

2020-12-01 13:38 UTC, merged