Disallow non-str indexing in reference dictionary
mdolab/baseclasses pull request #45
Opened 2021-02-17 21:17 UTC by nwu63

## Purpose
Explicitly raise `ValueError` when a non-string-based index is encountered. Previously, this got cast to `str` via the JSON writer, but causes inconsistencies between the JSON and python representation. Now, we just force everyone to cast to string in their own scripts first.

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

2021-02-17 21:55 UTC, eirikurj approved these changes

2021-02-17 22:16 UTC, galenng525 approved these changes

2021-02-17 22:17 UTC, sseraj requested changes
It should be `TypeError` I think.

2021-02-17 22:19 UTC, nwu63 commented
> It should be `TypeError` I think.

Oh shoot good call.

2021-02-17 22:23 UTC, sseraj submitted a review, later dismissed

2021-02-17 22:33 UTC, sseraj reviewed
Actually, black is failing

2021-02-17 23:05 UTC, sseraj approved these changes

2021-02-18 00:02 UTC, joanibal approved these changes

2021-02-18 00:02 UTC, merged